name: coinpro_prokit
description: A new Flutter project.
version: 2.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.4
  nb_utils: ^5.0.8-beta.2
  intl: ^0.18.1
  flutter_vector_icons: ^1.0.0
  google_fonts: ^5.0.0

 #STATE MANAGEMENT
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  # CoinPro
  dots_indicator: ^3.0.0

  syncfusion_flutter_charts: ^21.2.10
  cached_network_image: ^3.2.3
  flutter_slidable: ^3.0.0
  url_launcher: ^6.1.11
  smooth_page_indicator: ^1.1.0
  scan: 1.6.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - images/

